// Generated by gencpp from file infrastructure/AudFeatureResponse.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_AUDFEATURERESPONSE_H
#define INFRASTRUCTURE_MESSAGE_AUDFEATURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <infrastructure/AudFeatures.h>

namespace infrastructure
{
template <class ContainerAllocator>
struct AudFeatureResponse_
{
  typedef AudFeatureResponse_<ContainerAllocator> Type;

  AudFeatureResponse_()
    : features()  {
    }
  AudFeatureResponse_(const ContainerAllocator& _alloc)
    : features(_alloc)  {
  (void)_alloc;
    }



   typedef  ::infrastructure::AudFeatures_<ContainerAllocator>  _features_type;
  _features_type features;





  typedef boost::shared_ptr< ::infrastructure::AudFeatureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure::AudFeatureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AudFeatureResponse_

typedef ::infrastructure::AudFeatureResponse_<std::allocator<void> > AudFeatureResponse;

typedef boost::shared_ptr< ::infrastructure::AudFeatureResponse > AudFeatureResponsePtr;
typedef boost::shared_ptr< ::infrastructure::AudFeatureResponse const> AudFeatureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure::AudFeatureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure::AudFeatureResponse_<ContainerAllocator1> & lhs, const ::infrastructure::AudFeatureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.features == rhs.features;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure::AudFeatureResponse_<ContainerAllocator1> & lhs, const ::infrastructure::AudFeatureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::AudFeatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::AudFeatureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::AudFeatureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81e73fd091a8624334b5b3adb6e535ca";
  }

  static const char* value(const ::infrastructure::AudFeatureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81e73fd091a86243ULL;
  static const uint64_t static_value2 = 0x34b5b3adb6e535caULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/AudFeatureResponse";
  }

  static const char* value(const ::infrastructure::AudFeatureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/AudFeatures features\n"
"\n"
"================================================================================\n"
"MSG: infrastructure/AudFeatures\n"
"float64 min_f0 #minimum fundamental frequency\n"
"float64 max_f0 #maximum fundamental frequency\n"
"float64 mean_f0 #mean fundamental frequency\n"
"float64 min_int #minimum intensity\n"
"float64 max_int #maximum intensity\n"
"float64 mean_int #mean intensity\n"
"float64 jitter #local\n"
"float64 shimmer #local\n"
"float64 hnr #harmonic to noise ratio\n"
"float64 speaking_rate #of syllables per second\n"
;
  }

  static const char* value(const ::infrastructure::AudFeatureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.features);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudFeatureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure::AudFeatureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure::AudFeatureResponse_<ContainerAllocator>& v)
  {
    s << indent << "features: ";
    s << std::endl;
    Printer< ::infrastructure::AudFeatures_<ContainerAllocator> >::stream(s, indent + "  ", v.features);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_AUDFEATURERESPONSE_H
