// Generated by gencpp from file infrastructure/AudFeature.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_AUDFEATURE_H
#define INFRASTRUCTURE_MESSAGE_AUDFEATURE_H

#include <ros/service_traits.h>


#include <infrastructure/AudFeatureRequest.h>
#include <infrastructure/AudFeatureResponse.h>


namespace infrastructure
{

struct AudFeature
{

typedef AudFeatureRequest Request;
typedef AudFeatureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AudFeature
} // namespace infrastructure


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::infrastructure::AudFeature > {
  static const char* value()
  {
    return "b83fe3706a17dd745e1029708d72454b";
  }

  static const char* value(const ::infrastructure::AudFeature&) { return value(); }
};

template<>
struct DataType< ::infrastructure::AudFeature > {
  static const char* value()
  {
    return "infrastructure/AudFeature";
  }

  static const char* value(const ::infrastructure::AudFeature&) { return value(); }
};


// service_traits::MD5Sum< ::infrastructure::AudFeatureRequest> should match
// service_traits::MD5Sum< ::infrastructure::AudFeature >
template<>
struct MD5Sum< ::infrastructure::AudFeatureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::infrastructure::AudFeature >::value();
  }
  static const char* value(const ::infrastructure::AudFeatureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::infrastructure::AudFeatureRequest> should match
// service_traits::DataType< ::infrastructure::AudFeature >
template<>
struct DataType< ::infrastructure::AudFeatureRequest>
{
  static const char* value()
  {
    return DataType< ::infrastructure::AudFeature >::value();
  }
  static const char* value(const ::infrastructure::AudFeatureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::infrastructure::AudFeatureResponse> should match
// service_traits::MD5Sum< ::infrastructure::AudFeature >
template<>
struct MD5Sum< ::infrastructure::AudFeatureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::infrastructure::AudFeature >::value();
  }
  static const char* value(const ::infrastructure::AudFeatureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::infrastructure::AudFeatureResponse> should match
// service_traits::DataType< ::infrastructure::AudFeature >
template<>
struct DataType< ::infrastructure::AudFeatureResponse>
{
  static const char* value()
  {
    return DataType< ::infrastructure::AudFeature >::value();
  }
  static const char* value(const ::infrastructure::AudFeatureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_AUDFEATURE_H
