// Generated by gencpp from file infrastructure/EmoProb.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_EMOPROB_H
#define INFRASTRUCTURE_MESSAGE_EMOPROB_H

#include <ros/service_traits.h>


#include <infrastructure/EmoProbRequest.h>
#include <infrastructure/EmoProbResponse.h>


namespace infrastructure
{

struct EmoProb
{

typedef EmoProbRequest Request;
typedef EmoProbResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmoProb
} // namespace infrastructure


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::infrastructure::EmoProb > {
  static const char* value()
  {
    return "40d3f05c7b83a5fa6248bdf3d1b21e2e";
  }

  static const char* value(const ::infrastructure::EmoProb&) { return value(); }
};

template<>
struct DataType< ::infrastructure::EmoProb > {
  static const char* value()
  {
    return "infrastructure/EmoProb";
  }

  static const char* value(const ::infrastructure::EmoProb&) { return value(); }
};


// service_traits::MD5Sum< ::infrastructure::EmoProbRequest> should match
// service_traits::MD5Sum< ::infrastructure::EmoProb >
template<>
struct MD5Sum< ::infrastructure::EmoProbRequest>
{
  static const char* value()
  {
    return MD5Sum< ::infrastructure::EmoProb >::value();
  }
  static const char* value(const ::infrastructure::EmoProbRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::infrastructure::EmoProbRequest> should match
// service_traits::DataType< ::infrastructure::EmoProb >
template<>
struct DataType< ::infrastructure::EmoProbRequest>
{
  static const char* value()
  {
    return DataType< ::infrastructure::EmoProb >::value();
  }
  static const char* value(const ::infrastructure::EmoProbRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::infrastructure::EmoProbResponse> should match
// service_traits::MD5Sum< ::infrastructure::EmoProb >
template<>
struct MD5Sum< ::infrastructure::EmoProbResponse>
{
  static const char* value()
  {
    return MD5Sum< ::infrastructure::EmoProb >::value();
  }
  static const char* value(const ::infrastructure::EmoProbResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::infrastructure::EmoProbResponse> should match
// service_traits::DataType< ::infrastructure::EmoProb >
template<>
struct DataType< ::infrastructure::EmoProbResponse>
{
  static const char* value()
  {
    return DataType< ::infrastructure::EmoProb >::value();
  }
  static const char* value(const ::infrastructure::EmoProbResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_EMOPROB_H
