// Generated by gencpp from file infrastructure/EmoProbResponse.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_EMOPROBRESPONSE_H
#define INFRASTRUCTURE_MESSAGE_EMOPROBRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <infrastructure/EmoProbArr.h>

namespace infrastructure
{
template <class ContainerAllocator>
struct EmoProbResponse_
{
  typedef EmoProbResponse_<ContainerAllocator> Type;

  EmoProbResponse_()
    : emotion()  {
    }
  EmoProbResponse_(const ContainerAllocator& _alloc)
    : emotion(_alloc)  {
  (void)_alloc;
    }



   typedef  ::infrastructure::EmoProbArr_<ContainerAllocator>  _emotion_type;
  _emotion_type emotion;





  typedef boost::shared_ptr< ::infrastructure::EmoProbResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure::EmoProbResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EmoProbResponse_

typedef ::infrastructure::EmoProbResponse_<std::allocator<void> > EmoProbResponse;

typedef boost::shared_ptr< ::infrastructure::EmoProbResponse > EmoProbResponsePtr;
typedef boost::shared_ptr< ::infrastructure::EmoProbResponse const> EmoProbResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure::EmoProbResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure::EmoProbResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure::EmoProbResponse_<ContainerAllocator1> & lhs, const ::infrastructure::EmoProbResponse_<ContainerAllocator2> & rhs)
{
  return lhs.emotion == rhs.emotion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure::EmoProbResponse_<ContainerAllocator1> & lhs, const ::infrastructure::EmoProbResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::EmoProbResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::EmoProbResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::EmoProbResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab99b8f0752701b0809160a61e6ae0f6";
  }

  static const char* value(const ::infrastructure::EmoProbResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab99b8f0752701b0ULL;
  static const uint64_t static_value2 = 0x809160a61e6ae0f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/EmoProbResponse";
  }

  static const char* value(const ::infrastructure::EmoProbResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/EmoProbArr emotion\n"
"\n"
"\n"
"================================================================================\n"
"MSG: infrastructure/EmoProbArr\n"
"string emotion\n"
"float32 probability\n"
;
  }

  static const char* value(const ::infrastructure::EmoProbResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emotion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmoProbResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure::EmoProbResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure::EmoProbResponse_<ContainerAllocator>& v)
  {
    s << indent << "emotion: ";
    s << std::endl;
    Printer< ::infrastructure::EmoProbArr_<ContainerAllocator> >::stream(s, indent + "  ", v.emotion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_EMOPROBRESPONSE_H
