// Generated by gencpp from file infrastructure/FaceEmotions.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_FACEEMOTIONS_H
#define INFRASTRUCTURE_MESSAGE_FACEEMOTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <infrastructure/EmoProbArr.h>

namespace infrastructure
{
template <class ContainerAllocator>
struct FaceEmotions_
{
  typedef FaceEmotions_<ContainerAllocator> Type;

  FaceEmotions_()
    : data()  {
    }
  FaceEmotions_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::infrastructure::EmoProbArr_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::infrastructure::EmoProbArr_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::infrastructure::FaceEmotions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure::FaceEmotions_<ContainerAllocator> const> ConstPtr;

}; // struct FaceEmotions_

typedef ::infrastructure::FaceEmotions_<std::allocator<void> > FaceEmotions;

typedef boost::shared_ptr< ::infrastructure::FaceEmotions > FaceEmotionsPtr;
typedef boost::shared_ptr< ::infrastructure::FaceEmotions const> FaceEmotionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure::FaceEmotions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure::FaceEmotions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure::FaceEmotions_<ContainerAllocator1> & lhs, const ::infrastructure::FaceEmotions_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure::FaceEmotions_<ContainerAllocator1> & lhs, const ::infrastructure::FaceEmotions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::FaceEmotions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::FaceEmotions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::FaceEmotions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::FaceEmotions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::FaceEmotions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::FaceEmotions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure::FaceEmotions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58ee6432f72e3e9e760e1128d61daa6f";
  }

  static const char* value(const ::infrastructure::FaceEmotions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58ee6432f72e3e9eULL;
  static const uint64_t static_value2 = 0x760e1128d61daa6fULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure::FaceEmotions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/FaceEmotions";
  }

  static const char* value(const ::infrastructure::FaceEmotions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure::FaceEmotions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/EmoProbArr[] data\n"
"================================================================================\n"
"MSG: infrastructure/EmoProbArr\n"
"string emotion\n"
"float32 probability\n"
;
  }

  static const char* value(const ::infrastructure::FaceEmotions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure::FaceEmotions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceEmotions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure::FaceEmotions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure::FaceEmotions_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::infrastructure::EmoProbArr_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_FACEEMOTIONS_H
