// Generated by gencpp from file infrastructure/GazeResponse.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_GAZERESPONSE_H
#define INFRASTRUCTURE_MESSAGE_GAZERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure
{
template <class ContainerAllocator>
struct GazeResponse_
{
  typedef GazeResponse_<ContainerAllocator> Type;

  GazeResponse_()
    : gazedirection()  {
    }
  GazeResponse_(const ContainerAllocator& _alloc)
    : gazedirection(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _gazedirection_type;
  _gazedirection_type gazedirection;





  typedef boost::shared_ptr< ::infrastructure::GazeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure::GazeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GazeResponse_

typedef ::infrastructure::GazeResponse_<std::allocator<void> > GazeResponse;

typedef boost::shared_ptr< ::infrastructure::GazeResponse > GazeResponsePtr;
typedef boost::shared_ptr< ::infrastructure::GazeResponse const> GazeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure::GazeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure::GazeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure::GazeResponse_<ContainerAllocator1> & lhs, const ::infrastructure::GazeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.gazedirection == rhs.gazedirection;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure::GazeResponse_<ContainerAllocator1> & lhs, const ::infrastructure::GazeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::GazeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::GazeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::GazeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::GazeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::GazeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::GazeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure::GazeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60309a766d9048157607b5f232e2ee59";
  }

  static const char* value(const ::infrastructure::GazeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60309a766d904815ULL;
  static const uint64_t static_value2 = 0x7607b5f232e2ee59ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure::GazeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/GazeResponse";
  }

  static const char* value(const ::infrastructure::GazeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure::GazeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string    gazedirection\n"
;
  }

  static const char* value(const ::infrastructure::GazeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure::GazeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gazedirection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure::GazeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure::GazeResponse_<ContainerAllocator>& v)
  {
    s << indent << "gazedirection: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.gazedirection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_GAZERESPONSE_H
