// Generated by gencpp from file infrastructure/SttResponse.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_STTRESPONSE_H
#define INFRASTRUCTURE_MESSAGE_STTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure
{
template <class ContainerAllocator>
struct SttResponse_
{
  typedef SttResponse_<ContainerAllocator> Type;

  SttResponse_()
    : transcription()  {
    }
  SttResponse_(const ContainerAllocator& _alloc)
    : transcription(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _transcription_type;
  _transcription_type transcription;





  typedef boost::shared_ptr< ::infrastructure::SttResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure::SttResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SttResponse_

typedef ::infrastructure::SttResponse_<std::allocator<void> > SttResponse;

typedef boost::shared_ptr< ::infrastructure::SttResponse > SttResponsePtr;
typedef boost::shared_ptr< ::infrastructure::SttResponse const> SttResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure::SttResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure::SttResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure::SttResponse_<ContainerAllocator1> & lhs, const ::infrastructure::SttResponse_<ContainerAllocator2> & rhs)
{
  return lhs.transcription == rhs.transcription;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure::SttResponse_<ContainerAllocator1> & lhs, const ::infrastructure::SttResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::SttResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::SttResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::SttResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::SttResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::SttResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::SttResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure::SttResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d87ceb831c5fd1ff2239ff1c5b3dfc96";
  }

  static const char* value(const ::infrastructure::SttResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd87ceb831c5fd1ffULL;
  static const uint64_t static_value2 = 0x2239ff1c5b3dfc96ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure::SttResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/SttResponse";
  }

  static const char* value(const ::infrastructure::SttResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure::SttResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string transcription\n"
;
  }

  static const char* value(const ::infrastructure::SttResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure::SttResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transcription);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SttResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure::SttResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure::SttResponse_<ContainerAllocator>& v)
  {
    s << indent << "transcription: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.transcription);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_STTRESPONSE_H
