// Generated by gencpp from file infrastructure/TtsRequest.msg
// DO NOT EDIT!


#ifndef INFRASTRUCTURE_MESSAGE_TTSREQUEST_H
#define INFRASTRUCTURE_MESSAGE_TTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace infrastructure
{
template <class ContainerAllocator>
struct TtsRequest_
{
  typedef TtsRequest_<ContainerAllocator> Type;

  TtsRequest_()
    : text()  {
    }
  TtsRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::infrastructure::TtsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::infrastructure::TtsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TtsRequest_

typedef ::infrastructure::TtsRequest_<std::allocator<void> > TtsRequest;

typedef boost::shared_ptr< ::infrastructure::TtsRequest > TtsRequestPtr;
typedef boost::shared_ptr< ::infrastructure::TtsRequest const> TtsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::infrastructure::TtsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::infrastructure::TtsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::infrastructure::TtsRequest_<ContainerAllocator1> & lhs, const ::infrastructure::TtsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::infrastructure::TtsRequest_<ContainerAllocator1> & lhs, const ::infrastructure::TtsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace infrastructure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::TtsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::infrastructure::TtsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::TtsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::infrastructure::TtsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::TtsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::infrastructure::TtsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::infrastructure::TtsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::infrastructure::TtsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::infrastructure::TtsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "infrastructure/TtsRequest";
  }

  static const char* value(const ::infrastructure::TtsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::infrastructure::TtsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
;
  }

  static const char* value(const ::infrastructure::TtsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::infrastructure::TtsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TtsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::infrastructure::TtsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::infrastructure::TtsRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INFRASTRUCTURE_MESSAGE_TTSREQUEST_H
