# Generated by Django 4.2.4 on 2023-08-21 08:50

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpressiveFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emofacial", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FeaturesConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "hear",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("streaminput", "Stream Input"),
                            ("saveinput", "Save Input"),
                            ("voicefeatureextraction", "Voice Feature Extraction"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "talk",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("nlp", "NLP"),
                            ("tts", "TTS"),
                            ("emospeech", "Emotional Speech"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "express",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[("emofacial", "Emotional Facial Expression")],
                        max_length=25,
                    ),
                ),
                (
                    "move",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True, choices=[("move", "Move")], max_length=25
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JointConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListeningFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("streaminput", models.BooleanField(default=False)),
                ("saveinput", models.BooleanField(default=False)),
                ("voicefeatureextraction", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MotorConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("Type", "Servo"),
                            ("Type", "DC"),
                            ("Type", "Stepper"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovingFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TalkingFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nlp", models.BooleanField(default=False)),
                ("tts", models.BooleanField(default=False)),
                ("emospeech", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RobotConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="My_Robot", max_length=255)),
                (
                    "features",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setupWizard.featuresconfig",
                    ),
                ),
                ("joints", models.ManyToManyField(to="setupWizard.jointconfig")),
            ],
        ),
        migrations.AddField(
            model_name="jointconfig",
            name="dofs",
            field=models.ManyToManyField(to="setupWizard.motorconfig"),
        ),
    ]
