# Generated by Django 4.2.4 on 2023-08-21 08:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("setupWizard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpressiveFeatures",
        ),
        migrations.DeleteModel(
            name="ListeningFeatures",
        ),
        migrations.DeleteModel(
            name="TalkingFeatures",
        ),
        migrations.RemoveField(
            model_name="robotconfig",
            name="features",
        ),
        migrations.AddField(
            model_name="jointconfig",
            name="name",
            field=models.CharField(default="My_Joint", max_length=255),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="express",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("emofacial", "Emotional Facial Expression")],
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="hear",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("streaminput", "Stream Input"),
                    ("saveinput", "Save Input"),
                    ("voicefeatureextraction", "Voice Feature Extraction"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="move",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[("move", "Move")], max_length=25
            ),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="talk",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("nlp", "NLP"),
                    ("tts", "TTS"),
                    ("emospeech", "Emotional Speech"),
                ],
                max_length=25,
            ),
        ),
        migrations.DeleteModel(
            name="FeaturesConfig",
        ),
    ]
