# Generated by Django 4.2.4 on 2024-01-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setupWizard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotconfig",
            name="image",
            field=models.ImageField(default="default.png", upload_to="robot_images"),
        ),
    ]
