# Generated by Django 4.2.4 on 2023-08-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "setupWizard",
            "0002_delete_expressivefeatures_delete_listeningfeatures_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="robotconfig",
            name="express",
        ),
        migrations.RemoveField(
            model_name="robotconfig",
            name="hear",
        ),
        migrations.RemoveField(
            model_name="robotconfig",
            name="talk",
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="emofacial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="emospeech",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="nlp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="saveinput",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="streaminput",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="tts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="robotconfig",
            name="voicefeatureextraction",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="robotconfig",
            name="move",
            field=models.BooleanField(default=False),
        ),
    ]
