# Generated by Django 3.2.9 on 2023-10-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=20)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(default='Unknown', max_length=20)),
            ],
        ),
    ]
