# Generated by Django 4.2.6 on 2023-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_link',
            field=models.CharField(blank=True, default='localhost:8000/api/stream?path=sounds/<your_audio_path>', max_length=200, null=True),
        ),
    ]
