# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from infrastructure/AudFeatureRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import audio_common_msgs.msg
import std_msgs.msg

class AudFeatureRequest(genpy.Message):
  _md5sum = "20c7f3b9bce053570f9d04bd783346e3"
  _type = "infrastructure/AudFeatureRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """audio_common_msgs/AudioDataStamped audio

================================================================================
MSG: audio_common_msgs/AudioDataStamped
std_msgs/Header header
audio_common_msgs/AudioData audio

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: audio_common_msgs/AudioData
uint8[] data
"""
  __slots__ = ['audio']
  _slot_types = ['audio_common_msgs/AudioDataStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       audio

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AudFeatureRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.audio is None:
        self.audio = audio_common_msgs.msg.AudioDataStamped()
    else:
      self.audio = audio_common_msgs.msg.AudioDataStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.audio.header.seq, _x.audio.header.stamp.secs, _x.audio.header.stamp.nsecs))
      _x = self.audio.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.audio.audio.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.audio is None:
        self.audio = audio_common_msgs.msg.AudioDataStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.audio.header.seq, _x.audio.header.stamp.secs, _x.audio.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.audio.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.audio.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.audio.audio.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.audio.header.seq, _x.audio.header.stamp.secs, _x.audio.header.stamp.nsecs))
      _x = self.audio.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.audio.audio.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.audio is None:
        self.audio = audio_common_msgs.msg.AudioDataStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.audio.header.seq, _x.audio.header.stamp.secs, _x.audio.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.audio.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.audio.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.audio.audio.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from infrastructure/AudFeatureResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import infrastructure.msg

class AudFeatureResponse(genpy.Message):
  _md5sum = "81e73fd091a8624334b5b3adb6e535ca"
  _type = "infrastructure/AudFeatureResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """infrastructure/AudFeatures features

================================================================================
MSG: infrastructure/AudFeatures
float64 min_f0 #minimum fundamental frequency
float64 max_f0 #maximum fundamental frequency
float64 mean_f0 #mean fundamental frequency
float64 min_int #minimum intensity
float64 max_int #maximum intensity
float64 mean_int #mean intensity
float64 jitter #local
float64 shimmer #local
float64 hnr #harmonic to noise ratio
float64 speaking_rate #of syllables per second"""
  __slots__ = ['features']
  _slot_types = ['infrastructure/AudFeatures']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       features

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AudFeatureResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.features is None:
        self.features = infrastructure.msg.AudFeatures()
    else:
      self.features = infrastructure.msg.AudFeatures()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.features.min_f0, _x.features.max_f0, _x.features.mean_f0, _x.features.min_int, _x.features.max_int, _x.features.mean_int, _x.features.jitter, _x.features.shimmer, _x.features.hnr, _x.features.speaking_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.features is None:
        self.features = infrastructure.msg.AudFeatures()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.features.min_f0, _x.features.max_f0, _x.features.mean_f0, _x.features.min_int, _x.features.max_int, _x.features.mean_int, _x.features.jitter, _x.features.shimmer, _x.features.hnr, _x.features.speaking_rate,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.features.min_f0, _x.features.max_f0, _x.features.mean_f0, _x.features.min_int, _x.features.max_int, _x.features.mean_int, _x.features.jitter, _x.features.shimmer, _x.features.hnr, _x.features.speaking_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.features is None:
        self.features = infrastructure.msg.AudFeatures()
      end = 0
      _x = self
      start = end
      end += 80
      (_x.features.min_f0, _x.features.max_f0, _x.features.mean_f0, _x.features.min_int, _x.features.max_int, _x.features.mean_int, _x.features.jitter, _x.features.shimmer, _x.features.hnr, _x.features.speaking_rate,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
class AudFeature(object):
  _type          = 'infrastructure/AudFeature'
  _md5sum = 'b83fe3706a17dd745e1029708d72454b'
  _request_class  = AudFeatureRequest
  _response_class = AudFeatureResponse
