# Generated by Django 3.2.9 on 2023-10-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('button_color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('violet', 'Violet'), ('orange', 'Orange'), ('black', 'Black'), ('gray', 'Gray')], default='blue', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Command Categories',
            },
        ),
        migrations.CreateModel(
            name='CommandConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_parrot_voice_path_prefix', models.CharField(blank=True, default='./', max_length=256)),
                ('red_parrot_voice_path_postfix', models.CharField(blank=True, default='.wav', max_length=256)),
                ('blue_parrot_voice_path_prefix', models.CharField(blank=True, default='./', max_length=256)),
                ('blue_parrot_voice_path_postfix', models.CharField(blank=True, default='.wav', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Commands Config',
            },
        ),
        migrations.CreateModel(
            name='ParrotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('tag', models.CharField(choices=[('P_M', 'Parrot Movement'), ('P_V', 'Parrot Voice')], max_length=4)),
                ('priority', models.IntegerField(default=0)),
                ('arg', models.IntegerField(unique=True)),
                ('voice_file_name', models.CharField(blank=True, default='', max_length=512)),
                ('perform_time', models.IntegerField(default=5)),
                ('parrot_0', models.BooleanField(default=True)),
                ('parrot_1', models.BooleanField(default=True)),
                ('interface_button_emoji', models.CharField(choices=[('💃', '💃'), ("'😃🙂'", "'😃🙂'"), ("'😛😝'", "'😛😝'"), ("'😛'", "'😛'"), ("'😝'", "'😝'"), ("'😃'", "'😃'"), ("'🙂'", "'🙂'")], max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serialHandler.commandcategory')),
            ],
            options={
                'verbose_name_plural': 'Parrot Commands',
            },
        ),
        migrations.CreateModel(
            name='BlueParrotCommand',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('serialHandler.parrotcommand',),
        ),
        migrations.CreateModel(
            name='RedParrotCommand',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('serialHandler.parrotcommand',),
        ),
    ]
