# Generated by Django 4.2.6 on 2023-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emotionmodel_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionmodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='emotionmodel',
            name='face_video_url',
            field=models.CharField(blank=True, default='localhost:8000/api/stream?path=media/<your_video_path>', max_length=200),
        ),
    ]
