# Generated by Django 4.2.6 on 2023-11-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emotionmodel_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionmodel',
            name='face_video_url',
            field=models.CharField(blank=True, default='http://<localhost_ip>:8000/api/stream?path=media/videos/<your_video_name.format>', max_length=200),
        ),
        migrations.AlterField(
            model_name='emotionmodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
